[project]
name = "emailvalidator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "email-validator>=2.3.0",
    "ipython>=9.9.0",
]
[dependency-groups]
dev = [
    "ruff>=0.14.13",
]
[tool.ruff]
line-length = 88
